# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 379a31dbe0d9484690cd16d272ca0126eeae1dc7c7d9a8660a6d5d32f8d0a4033fc969e60dcfd0768b650c02515573c893b18c4f4ca28bae32b0570b5da1ca01

test:
  secret_key_base: 3920392c598698b7b268b32ed85d4e8cb78b95f31555b05367388623f6740081d4fdb0ad0cce6abaf7970a27c2afe2853dc0de882ef8d66e0a60ea99b217f5d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
